---
services:
  mydb:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: chaitu

  apache:
    image: httpd
    ports:
      - 9090:80
    links:
      - mydb:mysql

  php:
    image: php:7.2-apache
    links:
      - mydb:mysql
      - apache:httpd
...


